name: chrisroantree
favicon: null
layout_spectrum: 0.61446
typography_spectrum: 0.48073
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3f2f7'
    - '#1c1c1c'
    - '#938c7b'
    - '#413e39'
    - '#c6bda5'
  brandStrength: 0.6875
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
