name: chrisroantree
favicon: null
layout_spectrum: 0.91312
typography_spectrum: 0.87958
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d0f0a'
    - '#e0dfdb'
    - '#55514e'
    - '#948f8b'
    - '#b5b2ad'
  brandStrength: 0.75
  lightness: 0.25
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
